name: Build and create a release when tag is pushed

# Only deploy when a new tag is pushed
# git tag v0.n
# git push origin v0.n 
on:
    push:
        tags:
          - "v*.*-alpha"
          - "v*.*.*"
          - "v*.*"
    #     branches: [ main ]
    # pull_request:
    #     branches: [ main ] 

# Must match the project() name in CMakeLists.txt
env:
    APP_NAME: infones64

# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binaries and create release
jobs:
    build-release:
        runs-on: self-hosted
        name: Build and create release
        steps:
                 
          - name: Check out this repository with submodules
            uses: actions/checkout@v4
            with:
                submodules: recursive

          - name: Build all the .uf2 files
            run: |            
                 export N64_INST=$HOME/libdragon && \
                 make && \
                 ls -l infones64.z64

          - name: Create release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: |
                       infones64.z64 
                body_path: CHANGELOG.md
          
         
